Feature/yandex map links
ruamk/carma pull request #116
Opened 2021-03-03 09:00 UTC by blinaa

2021-03-03 17:52 UTC, daapp requested changes
Удалить лишнее и перезалить.

2021-03-03 17:52 UTC, daapp commented on carma-casepartner-fe/src/Pages/ShowService.elm
> +            -- Заявка: 666666 | Оплата: РАМК
Комментарий всё ещё актуален?

2021-03-03 17:52 UTC, daapp commented on carma-casepartner-fe/src/Utils.elm
> +    , WithToast
Новые функции для Toast  из этого файла не используются.

2021-03-04 09:14 UTC, blinaa commented
удалил

2021-03-04 11:36 UTC, daapp commented
Rejected because of invalid branch, should be feature/photo-api.
New PR was created.

2021-03-04 11:36 UTC, closed without merging